import type { Metadata } from "next";
import "@mantine/core/styles.css";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { Inter, Schibsted_Grotesk } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";

const inter = Inter({ subsets: ["latin"] });
const grotesk = Schibsted_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tietoevry WebPerf",
  description: "Generated by Lighthouse & Axe",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${inter.className} bg-slate-50 min-h-screen`}>
        <MantineProvider>
          <div
            className={cn(
              "bg-white min-h-screen max-w-[1200px] p-8 mx-auto border-x border-x-slate-200",
            )}
          >
            {children}
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
