import type { Metadata } from "next";
import "@mantine/core/styles.css";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tietoevry WebPerf",
  description: "Generated by Lighthouse & Axe",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body
        suppressHydrationWarning
        className={`${inter.className} bg-gray-100/90 h-dvh`}
      >
        <MantineProvider>
          <div
            className={cn(
              "min-h-screen max-w-[1600px] bg-gray-100/90 p-6 lg:p-12 mx-auto border-x border-slate-200",
            )}
          >
            {children}
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
